### PR TITLE
Pay My Freelance Money

### PR DESCRIPTION
**Pull request by justicodelife**
Can you pay my freelance money?
ive been dming you for past two weeks now asking for the money i worked hard on and  you aren't responding.
Stop being a freeloader and pay my money else ill release the source code of the app to public, that's all i can do.
ive filled a complaint against you in the discord server, if you dont pay they are gonna permma ban you.

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
Done

**Comment by justicodelife** [comment]
> Done

through which? paypal or payoneer

**Comment by justicodelife** [comment]
will delete this branch if i get confirmation

**Comment by justicodelife** [comment]
Still waiting for confirmation

**Pull request closed without merging**
